sudo: required

language: node_js

node_js:
  - "8.1.3"

cache: npm

service:
  - docker

stages:
  - build
  - name: deploy
    if: branch = master

install:
  - npm run -q build

script:
  - sudo apt-get update
  - sudo apt-get install git-core
  - git --version
  - docker build -t eco-web .