sudo: required

language: node_js
node_js:
  - "8.1.3"

stages:
  - build
  - name: deploy
    if: branch = master
 
jobs:
  include:
    - stage: build
      script: npm run -q build
    - stage: deploy
      script: skip