sudo: required

language: node_js

node_js:
  - "8.1.3"

cache: npm

service:
  - docker

stages:
  - build
  - name: deploy
    if: branch = master

## not needed, will be done by the docker build command
install:
  - npm run -q build

script:
  - docker build -t eco-web .