sudo: required

language: node_js
node_js:
  - "8.1.3"

service:
  - docker

stages:
  - build
  - name: deploy
    if: branch = master

before_install:
  - sudo apt-get update
  - sudo apt-get install git-core
  - git --version

jobs:
  include:
    - stage: build
      script: npm run -q build
    - stage: deploy
      script: docker build -t eco-web .